### ISSUE TITLE
Support "Info Panel" (incl. all other derivates) in text

### ISSUE THREAD

**Issue by jloeser** [hunyadi/md2conf#17] opened 2023-10-13 05:57 UTC
We already use an Info Panel for the generated-by message at the very top of the document.

Could we enable this feature also in the normal text including its derivatives ("Note", "Success", "Warning", "Error")? 

The current notation I am using in Markdown for such boxes (there is no concept of "Info Panels" in Markdown)  is:
```
Normal text.

> **_NOTE:_**
> This is my Note. There can be **many** lines.
> Last one is this one.

Normal text.
```

**Comment by hunyadi** [comment] 2023-10-16 21:35
Python-Markdown defines a syntax for [admonitions](https://python-markdown.github.io/extensions/admonition/). Under the hood, *md2conf* uses Python-Markdown for parsing documents. If we use the Python-Markdown syntax for admonitions, it would be relatively easy to convert them into Confluence info panels.

**Comment by hunyadi** [comment] 2023-10-17 12:38
Converting rST-style admonitions defined with the Python-Markdown syntax into Confluence structured macro panels has been implemented in the latest *master*, and will be released as [md2conf](https://pypi.org/project/markdown-to-confluence/) version 0.1.9 in PyPI once it is confirmed that it works as by design.

**Closed by hunyadi** 2023-10-17 12:38 UTC
